name: prac5
description: "pr9"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  flutter_cache_manager: ^3.4.1
  google_fonts: ^6.3.2
  logger: ^2.6.2
  get_it: ^8.2.0
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  go_router: ^16.3.0


  cupertino_icons: ^1.0.8
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

#  my_package:
#    git:
#      url: https://github.com/username/my_package.git
#      ref: main
#      path: lib
#
#
#  local_package:
#     path: ../example/local_package
